.gitignore, Caddyfile, frontend/Dockerfile, frontend/pnpm-lock.yaml
This PR adjusts configuration files for local development to be able to access the application for development at https://zoni.local
=> Adjust configuration to enable local development using https

frontend/src/app.css, frontend/src/app.html, frontend/src/routes/+page.svelte, frontend/src/routes/account/login/+page.svelte, frontend/src/routes/account/login/start_window.svelte, frontend/src/routes/account/password-reset/+page.svelte, frontend/src/routes/account/register/+page.svelte, frontend/src/routes/account/reset-password/+page.svelte, frontend/src/routes/account/settings/+page.svelte, frontend/src/routes/admin/+page.svelte, frontend/src/routes/create/+page.svelte, frontend/src/routes/dashboard/+page.svelte, frontend/src/routes/docs/+page.svelte, frontend/src/routes/docs/attribution/+page.svelte, frontend/src/routes/docs/develop/+page.svelte, frontend/src/routes/docs/import-from-kahoot/+page.svelte, frontend/src/routes/docs/pow/+page.svelte, frontend/src/routes/docs/privacy-policy/+page.svelte, frontend/src/routes/docs/roadmap/+page.svelte, frontend/src/routes/docs/self-host/+page.svelte, frontend/src/routes/docs/tos/+page.svelte, frontend/src/routes/edit/+page.svelte, frontend/src/routes/explore/+page.svelte, frontend/src/routes/import/+page.svelte, frontend/src/routes/play/+page.svelte, frontend/src/routes/search/+page.svelte, frontend/src/routes/user/[user_id]/+page.svelte, frontend/src/routes/view/[quiz_id]/+page.svelte
This PR adds additional branding adjustments and sets Poppins font as the default one.
=> Additional branding adjustments and set Poppins font as default

frontend/src/app.css, frontend/src/lib/components/buttons/gray.svelte, frontend/src/lib/dashboard/start_game.svelte, frontend/src/lib/navbar.svelte, frontend/src/lib/play/admin/question.svelte, frontend/src/lib/view_quiz/RatingComponent.svelte, frontend/src/routes/+layout.svelte, frontend/src/routes/+page.svelte, frontend/src/routes/view/[quiz_id]/+page.svelte
This PR improves several visual aspects of the application including:
- Dark and Light Colors.
- Genera appearance colors to fit branding.
- Forms to start the game.
- Pages to view the quiz.
=> Branding and look and feel improvements

frontend/src/lib/i18n/locales/en.json, frontend/src/lib/navbar.svelte, frontend/src/lib/play/admin/question.svelte, frontend/src/lib/play/question.svelte, frontend/src/lib/play/questions/check.svelte, frontend/src/lib/practice/question.svelte, frontend/src/routes/dashboard/+page.svelte
This PR adjusts several text styles on answers and other application parts to ensure the text is readable independent of the background color.
=> Adjust text styles to avoid contrast reading problems

frontend/src/app.html, frontend/src/routes/+page.svelte, frontend/src/routes/account/login/+page.svelte, frontend/src/routes/account/login/start_window.svelte, frontend/src/routes/account/password-reset/+page.svelte, frontend/src/routes/account/register/+page.svelte, frontend/src/routes/account/reset-password/+page.svelte, frontend/src/routes/account/settings/+page.svelte, frontend/src/routes/admin/+page.svelte, frontend/src/routes/create/+page.svelte, frontend/src/routes/dashboard/+page.svelte, frontend/src/routes/docs/+page.svelte, frontend/src/routes/docs/attribution/+page.svelte, frontend/src/routes/docs/develop/+page.svelte, frontend/src/routes/docs/import-from-kahoot/+page.svelte, frontend/src/routes/docs/pow/+page.svelte, frontend/src/routes/docs/privacy-policy/+page.svelte, frontend/src/routes/docs/roadmap/+page.svelte, frontend/src/routes/docs/self-host/+page.svelte, frontend/src/routes/docs/tos/+page.svelte, frontend/src/routes/edit/+page.svelte, frontend/src/routes/explore/+page.svelte, frontend/src/routes/import/+page.svelte, frontend/src/routes/play/+page.svelte, frontend/src/routes/search/+page.svelte, frontend/src/routes/user/[user_id]/+page.svelte, frontend/src/routes/view/[quiz_id]/+page.svelte
This PR replace the string Zoni® Games by Zoni® AI
=> Rename to Zoni AI

frontend/src/routes/edit/videos/+page.svelte
This PR disables the video compressor to try to keep the original codec on videos and allow them to be played on iPhones.
=> Bypass video compressor

classquiz/routers/storage.py
This PR is another attempt to enable mp4 videos on iPhone
Ensure Content-Length is specified: Modifies the server configuration to send the Content-Length header instead of Transfer-Encoding: chunked.
Include Range Header: Ensure the server supports and responds appropriately to Range requests. This can be crucial for video streaming on iOS devices.
=> Add content-length and range header to the storage

classquiz/routers/box_controller/embedded/socket.py, frontend/src/lib/play/admin/voting_results.svelte, frontend/src/lib/play/question.svelte
This PR enhances the application's text answer validation by ensuring that leading and trailing whitespaces are trimmed, duplicated whitespaces are removed, and case sensitivity is correctly handled based on the `case_sensitive` property. 
1. **Backend (`classquiz/routers/box_controller/embedded/socket.py`):**
- Added `clean_text_answer` function to trim and normalize text answers.
- Modified `submit_answer_fn` to clean text answers and check for case sensitivity.
- Updated logic to correctly count text answers based on the `case_sensitive` property.
2. **Frontend (`frontend/src/lib/play/admin/voting_results.svelte`):**
- Added `cleanTextAnswer` function to normalize text answers.
- Updated the answer counting logic to handle case sensitivity.
- Ensured text answers are correctly matched …
=> Improve Text Answer Validation by Trimming Whitespace and Handling Case Sensitivity

classquiz/config.py, frontend/src/lib/admin.svelte, frontend/src/lib/dashboard/main_slider.svelte, frontend/src/lib/editor/MediaComponent.svelte, frontend/src/lib/editor/settings-card.svelte, frontend/src/lib/editor/sidebar.svelte, frontend/src/lib/editor/uploader.svelte, frontend/src/lib/editor/uploader/Library.svelte, frontend/src/lib/i18n/locales/en.json, frontend/src/lib/play/title.svelte, frontend/src/lib/practice/title_screen.svelte, frontend/src/routes/edit/files/+page.svelte, frontend/src/routes/moderation/+page.svelte, frontend/src/routes/user/[user_id]/+page.svelte, frontend/src/routes/view/[quiz_id]/+page.svelte
This pull request introduces the ability to upload and play audio files within the application. The changes span multiple components and ensure that audio files are handled appropriately alongside existing image and video files.
**File:** `classquiz/config.py`
- **Addition:** Allowed MIME type for audio files (`audio/mpeg`) added to the list.
**File:** `frontend/src/lib/dashboard/main_slider.svelte`
- **Addition:** Function to ensure `.mp3` extension is present for audio files.
- **Addition:** Conditional rendering for audio files.
**File:** `frontend/src/lib/editor/MediaComponent.svelte`
- **Addition:** Audio type handling in media component.
**File:** `frontend/src/lib/editor/settings-card.svelte`
- **Addition:** Handling for audio cover media.
**File:** …
=> Audio File Upload and Playback Support

classquiz/__init__.py, classquiz/config.py, classquiz/routers/session.py, classquiz/utils.py
This PR introduces session management and user authentication features. Teachers can start activities by validating session IDs, creating users on the fly, and handling authentication tokens.
1. **`classquiz/__init__.py`**:
- Added the `session` router to the included routers list.
2. **`classquiz/config.py`**:
- Added configuration for Portal API with `validate_session_url` and `validate_session_token`.
3. **`classquiz/routers/session.py`**:
- Created a new session router to handle session validation and start activities.
- Implemented endpoints to validate sessions and start activities:
- `validate_session_endpoint`: Validates session IDs.
- `start_activity`: Validates the session, creates users if they don't exist, generates access tokens, and redirects to the activity page.
4. …
=> Added Session Management and User Authentication from Zoni Portal

frontend/src/routes/dashboard/+page.svelte
This PR removes quiztivity option when creating an activity.
=> Remove quiztivity button

frontend/src/lib/components/commandpalette.svelte, frontend/src/lib/i18n/locales/en.json, frontend/src/lib/landing/testimonials.svelte, frontend/src/lib/quiztivity/shares_popover.svelte, frontend/src/lib/view_quiz/RatingComponent.svelte, frontend/src/lib/view_quiz/imported_or_not.svelte, frontend/src/routes/+page.svelte, frontend/src/routes/controller/+page.svelte, frontend/src/routes/docs/(markdown)/features/custom-field/+page.svx, frontend/src/routes/docs/(markdown)/features/remote-control/+page.svx, frontend/src/routes/docs/(markdown)/quiz/question-types/multiple-choice/+page.svx, frontend/src/routes/docs/(markdown)/quiz/question-types/order/+page.svx, frontend/src/routes/docs/(markdown)/quiz/question-types/text/+page.svx, frontend/src/routes/docs/+page.svelte, frontend/src/routes/docs/develop/+page.svelte, frontend/src/routes/docs/import-from-kahoot/+page.svelte, frontend/src/routes/docs/pow/+page.svelte, frontend/src/routes/docs/privacy-policy/+page.svelte, frontend/src/routes/docs/roadmap/+page.svelte, frontend/src/routes/docs/self-host/+page.svelte, frontend/src/routes/docs/tos/+page.svelte, frontend/src/routes/import/+page.svelte, frontend/src/routes/user/[user_id]/+page.svelte, frontend/src/routes/view/+error.svelte, frontend/src/routes/view/[quiz_id]/+page.svelte
This PR adjusts text content. Also, I did deep research on the code to find missing replacements for "quiz" with "activity."
=> Corrections on the text content

frontend/src/lib/play/question.svelte, frontend/src/lib/play/questions/check.svelte
**Enhancement of Answer Submission**:
- Implemented a unified approach to handle answer submissions for different question types (ABCD, RANGE, CHECK, ORDER).
- Ensured that the selected answer is correctly captured and displayed upon submission.
1. **Answer Submission Refactor**:
- Created specific functions (`selectAnswer`, `selectRangeAnswer`, `selectCheckAnswer`, `select_complex_answer`) to handle answer submission for each question type.
- I added the `showPlayerAnswers` flag to control the display of submitted answers.
2. **Code Adjustments**:
- Modified `selected_answer` initialization to handle different types (`string | string[]`).
- Updated the CHECK type question handling logic to capture and emit selected answers correctly.
- Ensured the `text_answer` array was updated and …
=> Enhance Answer Submission for Question

classquiz/auth.py, classquiz/routers/session.py
**Changes:**
- Default avatar field populated to avoid errors.
- Updated `cache_account` function in `classquiz/auth.py` to store user data directly as JSON.
- Modified `get_user_from_mail` function to use the updated `cache_account` for consistency.
- Improved error handling in `start_activity` function in `classquiz/routers/session.py`.
**Impact:**
- Ensures consistent data storage in Redis.
- Enhances error handling during user creation.
=> Fix on the fly account creation from Zoni Portal

frontend/src/lib/play/question.svelte, frontend/src/lib/play/questions/check.svelte, frontend/src/lib/play/results_kahoot.svelte, frontend/src/lib/play/title.svelte
This pull request includes several enhancements and fixes to the application's question display and submit functionality from the participant perspective. Key improvements are detailed below.
**Changes:**
1. **General Layout Improvements:**
- Improved overall layout using Tailwind CSS for better responsiveness and consistency across different screen sizes.
2. **Timer and Answer Options Centering:**
- Ensured the circular timer is centered within the answer options for all question types.
- Adjusted the grid layout to use 85% of the vertical space for answer options, providing a more balanced and visually appealing layout.
3. **Submit Button Placement:**
- Moved the submit button to be consistently displayed at the bottom of the screen for all question types, ensuring it is always visible …
=> Participant UI and Functionality Improvements for two devices mode

frontend/src/lib/dashboard/start_game.svelte, frontend/src/lib/play/question.svelte, frontend/src/lib/play/questions/check.svelte, frontend/src/routes/admin/+page.svelte, frontend/src/routes/play/+page.svelte
- Ensure theme mode consistency by avoiding transparent backgrounds.
- Adjust dark background colors for better readability.
- Include browser component to detect dark mode preference.
- Improve the start game component for dark theme compatibility.
- Fix issues with one device mode.
- Adjust the check component to avoid scrolling on CHECK questions.
**Changes:**
- Added logic to handle dark mode and set appropriate background colors.
- Modified styles and components to align with dark theme requirements.
- Improved UI ensures all elements, including the submit button, are visible without scrolling.
- Minor fixes and enhancements are needed to improve the overall user experience.
=> Enhance Dark Theme Support and UI Adjustments

frontend/src/lib/play/admin/question.svelte, frontend/src/lib/play/question.svelte, frontend/src/lib/play/questions/check.svelte
This PR addresses layout and responsiveness issues in the quiz interface, ensuring a more consistent and user-friendly experience across different devices. And fix problems in One Device mode.
**Changes:**
1. **frontend/src/lib/play/admin/question.svelte**
- Removed dark text class for better readability and consistency.
2. **frontend/src/lib/play/question.svelte**
- Adjusted vertical alignment based on game mode for better visual flow.
- Limited image height to 28vh to prevent overlapping and ensure better use of screen space.
- Ensured buttons and player answer display are centered and responsive.
3. **frontend/src/lib/play/questions/check.svelte**
- Changed container height to 80% and aligned items to the top for better layout structure.
- Added margin-top to ensure proper spacing and …
=> Improve Responsiveness and Layout Consistency in Question Components

frontend/src/lib/play/question.svelte, frontend/src/lib/play/questions/check.svelte, frontend/src/routes/play/+page.svelte
This PR includes several key updates to enhance the `check` component's styling and ensure consistent button sizes across various question types:
1. **Removed CSS and Adopted Tailwind CSS**:
- Transitioned all custom CSS styles to Tailwind CSS utility classes for better maintainability and consistency.
2. **Button Size Consistency**:
- Ensured that buttons for options maintain the same size, providing a uniform look and feel across the component.
3. **Responsive Adjustments**:
- Reduced the vertical size of buttons in normal mode.
- Made necessary adjustments to handle text and button alignment in one-device mode.
4. **Specific Updates**:
- Fine-tuned the TEXT and RAGE type questions layout for one-device mode.
These changes aim to improve the user experience by providing a consistent and …
=> Refactor questions to ensure participant UI is responsive in both game modes

frontend/src/lib/play/admin/check_range.svelte, frontend/src/lib/play/admin/check_results.svelte, frontend/src/lib/play/admin/order_results.svelte, frontend/src/lib/play/admin/results.svelte, frontend/src/lib/play/admin/voting_results.svelte
This PR enhances the clarity and user experience for viewing results across different question types.
- Implemented functionality to show correct and incorrect answers for CHECK-type questions.
- Enhanced the results display to include the question for CHECK-type results.
- Added functionality to show the correct range answer in the results.
- Improved answer display for Text, ABCD, and Voting questions.
- Refactored the voting results to show the votes received for each option in the VOTING question while maintaining '✓' or '✗' for other question types.
**Files Changed:**
- `frontend/src/lib/play/admin/check_range.svelte`: New component to display range results.
- `frontend/src/lib/play/admin/check_results.svelte`: New component to display CHECK type results.
- …
=> Improve Answer Display for Different Question Types

frontend/src/app.css, frontend/src/app.html, frontend/src/lib/editor/AddNewQuestionPopup.svelte, frontend/src/lib/view_quiz/RatingComponent.svelte, frontend/src/routes/+layout.svelte, frontend/src/routes/dashboard/+page.svelte, frontend/src/routes/edit/files/+page.svelte, frontend/src/routes/play/+page.svelte, frontend/src/routes/view/[quiz_id]/+page.svelte, frontend/tailwind.config.cjs
- Improved text visibility for light mode on devices initially configured in dark mode.
- Enhanced background and border styling to maintain consistency across themes.
- Updated component styles for better contrast and readability in both light and dark modes.
**Details**:
- Added conditional styling for borders and text colors in `RatingComponent.svelte` and `+page.svelte` files.
- Updated global styles and HTML structure to avoid white flashing background on load.
- Enhanced popup styling in `+page.svelte` to improve input box visibility in light mode.
=> Fix light mode text issues in devices configured in dark mode

frontend/src/lib/admin.svelte, frontend/src/lib/dashboard/main_slider.svelte, frontend/src/lib/editor/MediaComponent.svelte, frontend/src/lib/editor/card.svelte, frontend/src/lib/editor/settings-card.svelte, frontend/src/lib/editor/sidebar.svelte, frontend/src/lib/editor/uploader/Library.svelte, frontend/src/lib/play/admin/question.svelte, frontend/src/lib/play/question.svelte, frontend/src/lib/play/title.svelte, frontend/src/lib/practice/title_screen.svelte, frontend/src/routes/edit/files/+page.svelte, frontend/src/routes/moderation/+page.svelte, frontend/src/routes/user/[user_id]/+page.svelte, frontend/src/routes/view/[quiz_id]/+page.svelte
- Improved the handling of audio files across multiple components.
- Ensured proper rendering of audio elements with appropriate styling.
- Replaced incorrect video tags for audio with proper audio tags.
- Refactored redundant code and optimized media checks.
- Ensured media components were displayed correctly for audio files.
- Enhanced user experience by fixing audio playback issues.
=> Enhance media handling for audio files

frontend/src/lib/play/admin/question.svelte
This is a small change to ensure there is a bit of white under the question.
=> Add small white space at the button of the question

frontend/src/routes/play/+page.svelte
This PR is an attempt to avoid the need of scrolling vertically on mobile devices in two-device mode.
=> Attempt to minimize the need to scroll vertically

frontend/src/lib/play/admin/game_not_started.svelte, frontend/src/lib/play/admin/voting_results.svelte, frontend/src/lib/play/join.svelte
1. Fix the image cutting from top in activity code dialog 
2. Added the missing word from game not started screen
3. Changed colors in UI of results of Text, voting and ABCD questions
4. Fix the overflowing text in results screen
=> Fixing and implementing UI of Question and Result

frontend/src/routes/account/controllers/+page.svelte, frontend/src/routes/account/settings/+page.svelte, frontend/src/routes/account/settings/security/+page.svelte, frontend/src/routes/user/[user_id]/+page.svelte
This PR changes text color to white from settings page.
=> Changed text color in settings

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/lib/play/admin/final_results.svelte
- Incorporated `svelte-icons` for visual appeal.
- Updated styling with Tailwind CSS for better spacing, typography, and responsiveness.
- Applied card-like design for final results with rounded corners and shadows.
- **Added `svelte-icons` to `package.json` dependencies.**
- **Updated `final_results.svelte` for enhanced visual presentation.**
=> Enhance Final Results Display

frontend/src/app.html, frontend/src/routes/explore/+page.svelte
This PR fixes error 500 on the `/explore route` when it was refresh
=> Fix error 500 explore route after refresh

frontend/src/lib/play/admin/controls.svelte, frontend/src/lib/play/admin/game_not_started.svelte, frontend/src/lib/play/admin/question.svelte, frontend/src/lib/play/admin/voting_results.svelte, frontend/src/lib/play/circular_progress.svelte, frontend/tailwind.config.cjs
This PR builds on the previous work in #52 by @AbhishekBante and includes the following additional enhancements:
- **Fluid UI Adjustments**: Improved the responsiveness of the admin page, ensuring a better user experience on low-resolution screens.
- **Audio Player Restoration**: Re-added the lobby audio player to enhance user engagement.
- Adjusted UI elements to be more fluid and responsive using Tailwind CSS, especially for low-resolution screens.
- Enhanced text sizing with fluid typography settings to ensure readability across various screen sizes.
- Restored the lobby audio player functionality.
- This is a first attempt to improve UI responsiveness in different screen sizes, but we need to improve it more in the future.
=> Improvements to Admin Page UI and Audio Player Restoration

frontend/src/lib/play/admin/controls.svelte, frontend/src/lib/play/admin/question.svelte, frontend/src/lib/play/admin/voting_results.svelte, frontend/src/lib/play/circular_progress.svelte
This PR implements: 
1. Fix UI of Quiz in low resolution screens.
2. Changed font size in result page and removed -rotate-45 to fix overlapping of other options in graph.
=> Fix the UI of QUIZ in low resolution screens

frontend/src/lib/play/admin/game_not_started.svelte, frontend/src/lib/play/question.svelte, frontend/src/lib/play/results_kahoot.svelte, frontend/src/routes/account/login/backup_component.svelte, frontend/src/routes/account/login/select_method.svelte, frontend/src/routes/account/login/totp_component.svelte, frontend/src/routes/account/login/webauthn_component.svelte, frontend/src/routes/play/+page.svelte
This PR does following improvements:
1. UI: Change Text of Results on Student's View
2. UI: Change Box Design of Participants' Answer
3. Change Text In Blue Box in game joining screen.
4. Change ClassQuiz to Zoni AI in login and related screen.
=> Text content and color update

frontend/src/lib/i18n/locales/de.json, frontend/src/lib/i18n/locales/en.json, frontend/src/lib/i18n/locales/es.json, frontend/src/lib/i18n/locales/fr.json, frontend/src/lib/i18n/locales/hu.json, frontend/src/lib/i18n/locales/it.json, frontend/src/lib/i18n/locales/ja.json, frontend/src/lib/i18n/locales/nb_NO.json, frontend/src/lib/i18n/locales/nl.json, frontend/src/lib/i18n/locales/pl.json, frontend/src/lib/i18n/locales/pt.json, frontend/src/lib/i18n/locales/tr.json, frontend/src/lib/i18n/locales/vi.json, frontend/src/lib/i18n/locales/zh_Hant.json, frontend/src/lib/inline-editor.svelte, frontend/src/lib/play/question.svelte
This PR implements 
1. Remove &nbsp; Characters from Display while creating a new quiz
2. Show Message on Participant's Screen When Didn't Answer
=> Remove white spaces while quiz creation and display message when no answers selected

frontend/src/lib/editor.svelte, frontend/src/lib/editor/TextEditorPart.svelte, frontend/src/lib/play/admin/check_range.svelte, frontend/src/lib/play/admin/final_results.svelte, frontend/src/lib/play/admin/question.svelte, frontend/src/lib/play/question.svelte, frontend/src/lib/play/questions/check.svelte
This PR builds upon @AbhishekBante's work in #61 and introduces several enhancements, bug fixes, and visual improvements to the quiz game editor and user interface.
**Changes**:
1. **Editor Case Sensitivity Fix**:
- Resolved an issue where the editor could not properly set the case sensitivity option for text-based questions. The problematic code has been commented out temporarily but not removed for further review.
2. **Multiple-Choice Questions**:
- Implemented validation to ensure that users must select at least two options for multiple-choice questions to proceed.
3. **Visual Enhancements**:
- Updated UI elements across multiple components (`check_range.svelte`, `final_results.svelte`, `question.svelte`, etc.) to improve the user experience.
- Improved button styles, text alignment, …
=> Improvements to Editor and Question Handling Features

frontend/src/routes/play/+page.svelte
This PR fixes a mistake introduced on #64
CC: @AbhishekBante
=> fixes the extra {#if} closing tag and ensures proper nesting

frontend/src/lib/play/admin/final_results.svelte
This PR removes a duplicate box of participant's score showing in final results.
=> Removed the duplicate your position box

frontend/src/lib/play/admin/final_results.svelte
This PR adds text color white to player name and their score in final result display.
=> added text color to player name and their score

frontend/src/lib/editor/uploader.svelte, frontend/src/lib/editor/uploader/Library.svelte, frontend/src/lib/helpers.ts, frontend/src/lib/i18n/locales/ar.json, frontend/src/lib/i18n/locales/de.json, frontend/src/lib/i18n/locales/en.json, frontend/src/lib/i18n/locales/es.json, frontend/src/lib/i18n/locales/fr.json, frontend/src/lib/i18n/locales/hu.json, frontend/src/lib/i18n/locales/it.json, frontend/src/lib/i18n/locales/ja.json, frontend/src/lib/i18n/locales/nb_NO.json, frontend/src/lib/i18n/locales/nl.json, frontend/src/lib/i18n/locales/pl.json, frontend/src/lib/i18n/locales/pt.json, frontend/src/lib/i18n/locales/tr.json, frontend/src/lib/i18n/locales/vi.json, frontend/src/lib/i18n/locales/zh_Hant.json, frontend/src/lib/navbar.svelte, frontend/src/lib/play/admin/question.svelte, frontend/src/lib/play/admin/results.svelte, frontend/src/lib/play/question.svelte, frontend/src/routes/view/[quiz_id]/+page.svelte
This PR implements the following commits:
1. This commit adds a condition to show top 5 students results in admin screen after every question instead of 4 students.
2. The default colors of options of question type text were old, updated to new default colors.
3. Added the text color when tab is active in navbar.
4. Updated a text from all translation files.
5. While creating or updating a quiz and selected library media, the close button is absent in library modal, without this button there is no way to close the modal. The close button is added to implement this feature.
=> UI and text changes

frontend/src/lib/editor/TextEditorPart.svelte, frontend/src/lib/editor/uploader/Library.svelte
This PR implements following:
1. Restrict answer inputs to a maximum of 100 characters during activity creation. It's only for questions of type text.
2. Uppercase the text.
=> Added limitation of max 100 letters in text editor

frontend/src/lib/play/question.svelte, frontend/src/routes/play/+page.svelte
This pull request is based on #80 by @AbhishekBante addresses several issues related to state management and performance optimization in the quiz application. The primary focus is to fix the problem where players could submit multiple answers and to improve the efficiency of `localStorage` usage.
---
1. **Fix Multiple Answers Submission:**
- **Issue:** Players were able to submit multiple answers due to improper state handling.
- **Solution:** Leveraged a state store (`gameState`) to manage the acknowledgment of submitted answers. Now, once a player submits an answer, the state is updated, preventing multiple submissions.
2. **Optimize `localStorage` Access:**
- **Issue:** Multiple reads and writes to `localStorage` were causing performance bottlenecks.
- **Solution:** …
=> Optimize localStorage Usage and Fix Multiple Answers Issue

classquiz/socket_server/__init__.py, frontend/src/lib/play/question.svelte
Time synchronization has been implemented for users who join late or refresh during an activity session. This feature ensures that they are correctly synced with the remaining question time.
Changes include:
- Time synchronization logic was added for both the backend and frontend.
- Backend updates to calculate and emit the remaining time.
- Frontend updates to receive and handle remaining time or timeout signals from the server.
=> Time synchronization after join late or refresh

frontend/src/lib/play/join.svelte, frontend/src/routes/play/+page.server.ts, frontend/src/routes/play/+page.svelte
- Improved handling of game pin by ensuring it is not overwritten if already set.
- Added logic to load game state from `localStorage` at the start to restore `game_pin`, `game_mode`, and `username` correctly.
- Refined condition checks for game pin length and user input.
- Cleaned up and optimized related code for better maintainability.
=> Ensure Correct Handling of Game Pin and LocalStorage on Join

frontend/src/lib/play/admin/controls.svelte
This PR fixes responsiveness issue of QR and join information.
=> Fix Join information responsiveness

frontend/src/lib/play/question.svelte, frontend/src/routes/play/+page.svelte
This PR fixes an issue where a user's submitted answer was not persisting correctly after being acknowledged by the server. This led to inconsistencies when the page was reloaded or when navigating between questions.
- **Moved State Management to Parent Component (`+page.svelte`):**
- Shifted `selected_answer` and `acknowledgement` variables from `question.svelte` to `+page.svelte` to maintain a single source of truth.
- Passed `selected_answer` and `acknowledgement` as props to `question.svelte` for consistent state sharing.
- **Enhanced State Persistence:**
- Updated `storeState()` in `+page.svelte` to include `selected_answer` and `acknowledgement` in `localStorage`.
- Modified `restoreState()` to retrieve these values during component initialization.
- **Simplified …
=> Fix persistence of user's answer state after submission

frontend/src/routes/+page.svelte
This PR Adds an activity code form in landing page of games. This can only be seen by unauthorized users, after entering the the activity code it will redirect user to /play with the entered pin that way they will need to enter username directly.
=> Added the Activity code form on landing page

frontend/src/lib/play/admin/check_results.svelte, frontend/src/lib/play/admin/game_not_started.svelte, frontend/src/lib/play/admin/question.svelte
This PR fixes text overflow issues and inequal sizes of options with long text.
=> Fix Text overflow and equal sizes of options with long text

frontend/src/lib/editor/ABCDEditorPart.svelte, frontend/src/lib/editor/OrderEditorPart.svelte, frontend/src/lib/editor/VotingEditorPart.svelte
This PR adds restriction to add 100 max characters while creating options for every type of questions. It was implemented earlier but only for text questions and not other questions.
=> Added restriction to add 100 characters max while setting options

frontend/src/lib/editor.svelte, frontend/src/lib/play/admin/question.svelte
1. If the options were 2 in text questions then they were displayed one below another, changed it to display them side by side.
2. When admin creates a new activity they are able to save the activity even when they haven't selected atleast one single answer for question types ABCD and Check. Added a validation logic to ensure the admin won't be able to save the activity when no correct answer is selected.
=> Added validation to add atleast one correct answer while creating activity

frontend/src/lib/editor/card.svelte, frontend/src/lib/inline-editor.svelte, frontend/src/lib/yupSchemas.ts
This PR adds the maximum limit of 60 characters on question titles.
=> Added maximum limit for question title of 60 characters

frontend/src/lib/editor.svelte
This PR adds a limit to the number of correct answers in ABCD type questions and optimized error handling while validating the quiz data.
=> Select only one correct answer in ABCD type question

frontend/src/lib/editor.svelte, frontend/src/lib/yupSchemas.ts
1. Fix save quiz with the question type range. Since for some reason we cannot save quiz with range type questions.
2. Removed unnecessary errors that were seen on top of quiz.
3. Added the question no. in errors to clarify the error.
=> The validation fixes and improvements

frontend/src/lib/editor.svelte
This PR fixes the validation issues while saving old quizes.
=> Fix validations

frontend/src/lib/play/admin/check_results.svelte, frontend/src/lib/play/question.svelte, frontend/src/lib/play/questions/check.svelte
This pull request introduces improvements and fixes to the admin results page, particularly in handling check choice results when using images in questions. The changes include:
- **Design Enhancements:**
- Improved layout for displaying question results in a grid format for better readability and consistency.
- Implemented dynamic color contrast to ensure proper text readability based on background color brightness.
- **Bug Fixes:**
- Fixed an issue where image-based check choice questions were incorrectly flagged as incorrect, ensuring correct validation of image answers.
- Removed unnecessary bindings on the MediaComponent for optimization and performance improvement.
=> Improve Admin Results Page Design and Bugfix for Image-Based Check Questions

frontend/src/lib/play/questions/check.svelte, frontend/src/lib/practice/question.svelte
This PR introduces enhancements to the practice mode, focused on improving user interaction and visual clarity:
- **Image Support in Answers**: Added functionality to display images for questions where the answer type is an image. Images are shown in a responsive manner, ensuring they fit within the designated area without overlapping other UI elements.
- **Improved Button Behavior**: Adjusted the behavior of choice option buttons during practice to ensure better feedback when users select or disable answers. This includes dynamic styling to indicate the correct and incorrect answers once results are shown.
- **Answer Feedback Styling**: Updated button styles for improved visibility and user experience, especially when displaying the correct and incorrect answers in check-type questions. …
=> Enhance Practice Mode with Image Display and Improved Answer Button Behavior

frontend/src/lib/admin.svelte, frontend/src/lib/play/admin/question.svelte, frontend/src/lib/play/circular_progress.svelte
Updated Admin route layouts in `admin.svelte`, `question.svelte`, and `circular_progress.svelte` to enhance responsiveness and visual structure.
- Implemented a fluid design to reduce scrolling on the admin questions page.
- Adjusted margins, paddings, and element sizes to better fit various screen sizes.
- Improved the display of question types and answer options for better user experience.
- Refined the `CircularTimer` and question image handling to maintain consistency across different layouts.
- Reduced the size of the progress circle for a more compact interface.
=> Improve Fluid Design on Admin Questions Page

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/lib/play/question.svelte
This PR introduces the initial implementation of the drag-and-drop interface for `ORDER` type questions using the `svelte-dnd-action` package. The reason for implementing this is that #119 could not fix the issue. Also, the UI wastes a lot of vertical space. With this implementation of drag-and-drop functionality, we expect a better UI and a more intuitive interaction when answering ordering questions.  Key changes include:
- **Drag-and-Drop Functionality**: Integrated drag-and-drop support for ordering answers in `ORDER` type questions, allowing users to rearrange answers easily.
- **Layout Adjustments**: Improved layout for better user experience:
- Added a scrollable area for items, ensuring a smoother interaction on longer lists.
- Placed the submit button at the bottom of the …
=> First working drag-and-drop interface for order questions

frontend/src/lib/play/title.svelte, frontend/src/routes/play/+page.svelte
Added smooth scroll-to-top functionality after setting a new question or starting the game. Also made minor adjustments to the Activity Title component for better alignment and responsiveness.
=> Added scroll-to-top functionality after setting a new question or starting the game

frontend/src/lib/play/admin/question.svelte, frontend/src/lib/play/circular_progress.svelte
This PR adds size parameters to the circular timer to control the size of different application components that use this element.
=> Add circular timer size parameters

frontend/src/lib/editor.svelte, frontend/src/lib/play/question.svelte, frontend/src/lib/yupSchemas.ts
1. Adjust image size on participant's screen after selecting an answer of type image.
2. Added a max character limitation of 140 while creating a new question with the appropriate message.
3. Number of correct answers in multiple choice question is set to 1 or more.
=> Adjust image size, Character limitation and number of answers

frontend/src/lib/editor/OrderEditorPart.svelte, frontend/src/lib/play/question.svelte
This PR styles the drag and drop feature.
=> Style drag and drop feature

frontend/src/lib/components/DownloadQuiz.svelte, frontend/src/lib/components/commandpalette.svelte, frontend/src/lib/dashboard/start_game.svelte, frontend/src/lib/editor.svelte, frontend/src/lib/editor/AddNewQuestionPopup.svelte, frontend/src/lib/editor/OrderEditorPart.svelte, frontend/src/lib/editor/card.svelte, frontend/src/lib/editor/settings-card.svelte, frontend/src/lib/editor/sidebar.svelte, frontend/src/lib/editor/uploader.svelte, frontend/src/routes/dashboard/+page.svelte
This PR implements drag and drop for list of questions while activity creation.
=> Working Drag and drop feature for list of questions while creating activity

frontend/src/lib/play/question.svelte
This PR centers the options of question type order vertically.
=> Center order options vertically

frontend/src/routes/play/+page.svelte
This PR introduces toast notifications to improve the participant experience by informing them of connection and reconnection events during the activity. The following changes have been made:
- **Added `showToastOnce` function**: Ensures toast messages are not shown multiple times within a short period.
- **Added toast notifications for connection events**: Displays a toast when the client successfully reconnects or connects to the server.
- **Improved disconnection handling**: A toast is displayed when the connection is lost, with retry attempts.
- Added toast notification logic for connection and reconnection (`handleConnect`, `handleReconnect`, `handleDisconnect`).
- Adjusted socket event listeners for cleaner setup and teardown (`onMount`, `onDestroy`).
- Debounced toast notifications …
=> Add toast notifications for connection and reconnection events

classquiz/socket_server/__init__.py, frontend/src/lib/admin.svelte, frontend/src/lib/play/join.svelte, frontend/src/lib/play/question.svelte, frontend/src/lib/socket.ts, frontend/src/lib/socketManager.ts, frontend/src/routes/admin/+page.svelte, frontend/src/routes/play/+page.svelte
This PR addresses several improvements and fixes related to socket management and the rejoining process in activities, along with UX enhancements. Key changes include:
- **Socket.IO Refactor**: Centralized the event listener management by introducing a `socketManager` to avoid duplicated listeners and streamline event handling.
- **Rejoining Game**: Ensured proper restoration of game state, including scores, current question, and answers, for players who rejoin mid-game.
- **UX Enhancements**:
- Added `toast` notifications for connection events (connect, disconnect).
- Enhanced the rejoining flow by sending scores and questions only when necessary.
- Prioritized game pin retrieval from URL over local storage to ensure correct session continuity.
- Added socket event manager to avoid …
=> Refactor Socket Management and Improve Rejoin Flow with UX Enhancements

frontend/src/lib/components/Hamburger.svelte, frontend/src/lib/editor.svelte, frontend/src/lib/editor/ABCDEditorPart.svelte, frontend/src/lib/editor/AddNewQuestionPopup.svelte, frontend/src/lib/editor/TextEditorPart.svelte, frontend/src/lib/editor/card.svelte, frontend/src/lib/editor/settings-card.svelte, frontend/src/lib/editor/sidebar.svelte, frontend/src/lib/editor/uploader.svelte, frontend/src/lib/inline-editor.svelte
1. This is the first draft of responsive activity creation screen.
2. Introduced a hamburger component.
=> First draft of activity creation fluid design
