frontend/src/lib/play/question.svelte
Add a little bit of space to avoid overlapping images on input questions.
=> Add top margin to input box label to avoid overlaping

classquiz/routers/storage.py, frontend/src/lib/admin.svelte, frontend/src/lib/dashboard/main_slider.svelte, frontend/src/lib/editor/MediaComponent.svelte, frontend/src/lib/editor/settings-card.svelte, frontend/src/lib/editor/sidebar.svelte, frontend/src/lib/editor/uploader/Library.svelte, frontend/src/lib/play/title.svelte, frontend/src/lib/practice/title_screen.svelte, frontend/src/routes/edit/files/+page.svelte, frontend/src/routes/moderation/+page.svelte, frontend/src/routes/user/[user_id]/+page.svelte, frontend/src/routes/view/[quiz_id]/+page.svelte
This PR attempts to make Safari on Apple devices recognize and reproduce mp4 videos by adding the mp4 extension.
This adjusts the download endpoint to accept the mp4 extension and return the file, including the extension.
=> Add mp4 extension to videos

classquiz/socket_server/__init__.py, frontend/src/lib/play/admin/controls.svelte
This PR introduces functionality to automatically display the first question when a game starts. It ensures a smooth transition from the lobby to the first question, enhancing the user experience.
1. **Backend (Python):**
- Modified `start_game` event in `classquiz/socket_server/__init__.py` to automatically set the first question by calling `set_question_number` with the index `0`.
2. **Frontend (Svelte):**
- Added socket event listeners in `controls.svelte` to handle `set_question_number` and `start_game` events, ensuring the first question is shown when the game starts.
These changes should make the transition from the game lobby to the first question seamless and intuitive for users.
=> Automatically Show First Question on Game Start

frontend/src/lib/editor/settings-card.svelte, frontend/src/lib/editor/uploader.svelte
This PR enhances the media upload functionality for the `settings-card.svelte` and `uploader.svelte` components. It allows images and audio files to be uploaded and correctly set as `cover_image` or `background_image`. Additionally, it ensures that audio files can be uploaded and set for individual questions.
In the past, uploading media from the editor was not working smoothly, and it was necessary to use the file browser as a workaround.
- **Settings Card (`settings-card.svelte`):**
- Added support for uploading audio files and setting them as `cover_image`.
- Ensured the `contentTypes` dictionary includes the audio content type.
- Updated the `cover_image` handling to support images, videos, and audio files.
- Ensured correct functionality of setting and removing media types (image, …
=> Update Media Upload Functionality for Settings Card and Questions

frontend/src/lib/play/admin/order_results.svelte, frontend/src/lib/play/admin/results.svelte
This PR adds a new feature to display the correct order of quiz answers in a visually appealing and responsive format. The component adapts to both light and dark modes.
- **New Component**: Added `OrderResults` component to display answers in the correct order.
- **Responsive Design**: Ensured the component is responsive and visually consistent across devices.
- **Dark Mode Support**: Implemented dark mode support for better readability.
- `frontend/src/lib/play/admin/order_results.svelte`: Added the new `OrderResults` component.
- `frontend/src/lib/play/admin/results.svelte`: Integrated `OrderResults` component into the results display logic.
This enhancement improves the quiz experience by clearly showcasing the correct answer order with visual aids and responsiveness.
=> Display Correct Order for Order Activity

frontend/src/lib/admin.svelte, frontend/src/lib/dashboard/start_game.svelte, frontend/src/lib/editor/OrderEditorPart.svelte, frontend/src/lib/play/admin/check_range.svelte, frontend/src/lib/play/admin/controls.svelte, frontend/src/lib/play/admin/game_not_started.svelte, frontend/src/lib/play/admin/question.svelte, frontend/src/lib/play/admin/results.svelte, frontend/src/routes/+layout.svelte, frontend/src/routes/dashboard/+page.svelte, frontend/src/routes/view/[quiz_id]/+page.svelte
This PR addresses the following issues based on #38, created by @AbhishekBante :
- The start game modal background did not cover the entire page, causing a jarring effect when scrolling.
- The colors for order-type question options were inconsistent with the updated color scheme.
- The QR code size was too small upon clicking.
- UI elements such as the red timer line and control components overlapped during question display.
**Modifications:**
- Set the start game modal to a `fixed` display to ensure full-page coverage.
- Updated default colors for order-type question options.
- Increased the QR code size for better visibility.
- Adjusted the display properties to prevent overlapping the red timer line and control components.
These changes minimize teachers' need for vertical scrolling, …
=> Fix Background and UI Overlaps in Game Modal and Question Display

frontend/src/routes/+layout.svelte
The attempt in #42 was not enough to ensure the participant scrolling down was not enabled on the participant's mobile device. This PR is another attempt to modify the general layout.
=> Adjust layout to eliminate scrolling down if it is unnecessary

frontend/src/lib/play/admin/game_not_started.svelte, frontend/src/lib/play/join.svelte, frontend/src/lib/play/results_kahoot.svelte, frontend/src/routes/+layout.svelte, frontend/src/routes/admin/+page.svelte
This is another attempt to eliminate the need for vertical scrolling for participants. This PR eliminates `min-h` and `min-v`. That way, the screen area does not overflow.
=> Another attempt solve vertical scrolling problem

classquiz/socket_server/__init__.py, frontend/src/lib/play/question.svelte
This PR ensures that the display of answers is updated correctly for each participant. The `showPlayerAnswers` state now only affects the current player, preventing old submitted questions from appearing in the toast notifications.
- **Backend:** Emit `answer_acknowledged` event after submitting an answer.
- **Frontend:** Update `showPlayerAnswers` state upon receiving `answer_acknowledged` event.
**Note:** @AbhishekBante @Maria-CSV, we should test not only joining one participant but, if possible, joining more than one to detect this kind of bug.
=> Fix display answers per participant

classquiz/socket_server/__init__.py, frontend/src/routes/play/+page.svelte
- Added functionality to inform users about the reason for disconnection in both the client (`+page.svelte`) and server (`__init__.py`) components.
- Implemented new socket events for `connect_error`, `reconnect_failed`, and `disconnect_reason` to display appropriate messages to the user in the browser.
- Modified the `kick_player` event to emit a custom disconnect reason when a player is kicked from the game.
**Changes:**
- **`classquiz/socket_server/__init__.py`**:
- Added new logic to handle user disconnection reasons and emit them via `disconnect_reason`.
- Improved the `kick_player` function to notify the kicked player of the specific reason.
- **`frontend/src/routes/play/+page.svelte`**:
- Implemented `handleDisconnection` function to manage and display disconnection reasons in the …
=> Improve Disconnection Handling

frontend/src/lib/play/admin/final_results.svelte, frontend/src/lib/play/question.svelte
1. Change text color of your score in light mode since it was blue which was making it invisible.
2. In mobile view and one device mode, if no option is selected, the participant needs to scroll to see the message, therefore added dynamic height class to this block.
=> Text color of your score block in light mode and height of no ans selected block

frontend/src/routes/dashboard/+page.svelte
Problem: 
When logging in, the dashboard doesn't show previously created quizzes by user, to get them we first need to navigate to other page and revisit the dashboard. This issues persists when you refresh the page also.
Fix: 
Fetching data directly from page.svelete instead of page.ts, the page.ts is used to fetch data from db or API but it wasn't working as intended therefore in this fix we are fetching the data directly from page.svelete.
=> Fix data showing in dashboard

classquiz/__init__.py, classquiz/routers/game_state.py, classquiz/socket_server/__init__.py, frontend/src/routes/play/+page.svelte
This pull request introduces the ability for participants to join an ongoing activity after it has already started. Previously, new participants were unable to enter once the activity began. With this update, late joiners can seamlessly integrate into the activity, receive the current state, and participate in the remaining questions.
Key Changes:
- Updated `join_game` event handling in `socket_server` to allow late participants to join ongoing games.
- Added logic to broadcast the current game state (including the current question) to late joiners.
- Introduced new API endpoint `/api/v1/game_state/{game_pin}` to fetch the game state for rejoining participants.
- Enhanced the frontend Svelte component to handle late joins by fetching the game state and updating the UI accordingly.
- …
=> Allow Late Join in Activity

frontend/src/lib/play/question.svelte, frontend/src/routes/play/+page.svelte
Issue: 
When a participant joins and quiz starts, player selects an answer then the answer is recorded but when user refreshes the page they get the same options again and therefore they can submit answer again even though they already answered the question.
Solution: 
Saved the answer selected and acknowledgment in local storage so if the same user joins again or refreshes the page it populates the selected answer and restrict player to not record their answer again.
=> Fix issue of multiple answers by same user

frontend/src/lib/admin.svelte, frontend/src/lib/play/admin/controls.svelte
This pull request is based on #81 by @AbhishekBante, which introduces functionality to display a QR code and a link on the admin interface, allowing participants to join the activity at any time. The addition aims to enhance the user experience by providing easy access for participants to join the game without manually entering the game PIN.
1. **frontend/src/lib/admin.svelte**
- **Added** `export let game_pin: string;` to pass the game PIN to child components.
- **Passed** the `game_pin` prop to the `controls` component:
```svelte
{#if show_controls}
<Controls
...
{game_pin}
/>
{/if}
```
2. **frontend/src/lib/play/admin/controls.svelte**
- **Imported** `fade` from `svelte/transition` for transition effects.
- **Added** `export let game_pin: string;` to receive the game …
=> Add QR Code and Link to Facilitate Participant Joining at Any Time

frontend/src/routes/play/+page.svelte
This PR is based on #86 by @AbhishekBante. It added a refactored game state restoration to simplify `onMount` logic by consolidating redundant calls. It also removed duplicate `noSleep` initialization and streamlined game pin handling within `restoreState`.
=> Fix player joining refresh problem when pin parameter is not included.

frontend/src/routes/play/+page.svelte
Issue: 
When the player refresh the page they see a form to enter activity code and username even though they did joined the game.
Expected Reason: 
This issue was in page.server.ts of play directory, it was fetching the game pin from params and returning to page.ts and since the params was empty the game_pin was empty too. And in restoreState function, it is first fetching game pin from local storage and compares it with the game_pin since the game_pin is empty, the function was clearing the localstorage and then player is needed to enter game pin again.
Solution:
Populated the game_pin onMount from localstorage.
=> Fix player quiz joining

frontend/src/lib/play/question.svelte, frontend/src/routes/play/+page.svelte
This PR fixes an issue where refreshing the page twice on mobile devices, particularly iOS devices, caused the game state to be lost, requiring users to re-enter their names. The problem was due to the unreliable firing of the `beforeunload` event on mobile Safari.
- **Replaced `beforeunload` Event:**
- Removed the `beforeunload` event listener in `+page.svelte`.
- Added `pagehide` and `visibilitychange` event listeners to reliably detect when the page is being hidden or the visibility changes, ensuring `storeState()` is called appropriately.
- **Ensured `storeState()` is Called from `question.svelte`:**
- In `question.svelte`, added a `createEventDispatcher` to dispatch a custom `storeStateNeeded` event whenever the state needs to be saved.
- In `+page.svelte`, listened …
=> Fix state loss on mobile by replacing `beforeunload` with `pagehide` and `visibilitychange`

frontend/src/lib/play/admin/final_results.svelte, frontend/src/lib/play/question.svelte, frontend/src/routes/play/+page.svelte
Issue:
There were some texts that were translating even though the English restriction was "on" for the particular quiz . Those were the submit buttons, and position information on final results screen.
=> Fix text translating even with english restrictions

classquiz/routers/game_state.py, classquiz/socket_server/__init__.py, frontend/src/lib/play/question.svelte, frontend/src/routes/play/+page.svelte
This PR fixes an issue where late joiners were able to submit answers even after the admin had revealed the solutions, which should not be allowed. The key changes include:
- **Game State Management**:
- Updated the `question_show` flag to `false` when the admin selects "Show Solutions" or when time is up, ensuring that no further answers can be submitted.
- Included the `question_show` state in the data sent to players during `join_game`, `rejoin_game`, and `set_question_number` events, so late joiners receive the correct game state.
- **Server-Side Updates** (`classquiz/socket_server/__init__.py`):
- Modified the `show_solutions` event handler to set `question_show = False` and save the updated game data back to Redis.
- Adjusted `submit_answer` to prevent answer submissions if time has …
=> Prevent Late Joiners from Submitting Answers After Solutions Are Shown

frontend/src/lib/play/join.svelte, frontend/src/routes/play/+page.svelte
These changes enhance the integrity of game sessions by preventing participants from joining activities that have already concluded.
- **Added `gameEnded` flag** to track when a game session has been finalized.
- **Implemented checks** in `join.svelte` and `+page.svelte` to verify if a game has ended before allowing a user to join.
- **Alert and redirect** users attempting to join an ended game to the main `/play` page, ensuring the game state is not stored post-finalization.
=> Prevent Joining Finalized Game Sessions

frontend/src/lib/play/question.svelte, frontend/src/routes/play/+page.svelte
This PR resolves an issue where, in some instances using the Opera browser, participants were erroneously allowed to resubmit answers after their original response had already been acknowledged. 
Key changes include:
- Replacing instances of `showPlayerAnswers` with `acknowledgement.answered` for more reliable state handling.
- Updated conditional checks to ensure that once an answer is acknowledged, participants are prevented from resubmitting answers.
These improvements ensure a more consistent experience across all browsers, preventing accidental re-answers post-submission.
=> Fix for random issue allowing participants to answer after showing answers in Opera browser

frontend/src/lib/play/admin/question.svelte
This PR fixes the size of options, if the text is small in options then the box should be normal as before, currently this box is too big even when the text is small.
=> fix oversized width of options

frontend/src/lib/play/admin/question.svelte, frontend/src/lib/play/question.svelte
1. While in questions of type range, even if participants didn't submit any answer, the default answer which is middle number of range bar automatically gets submitted. Fixed it by commenting statement which was initializing the range selected answer.
2. Added the same styling to type text options as styled to other question type options.
=> Fix responsiveness and automatic answer submission in question type range

classquiz/socket_server/__init__.py, frontend/src/routes/play/+page.svelte
This PR addresses an issue where a player, who has already submitted an answer during an ongoing question, would see the option to select an answer again upon refreshing the page. This behavior is incorrect as the player has already answered the question, and reselecting would not be allowed while the question is still active.
**Problem Description:**
When a player submits an answer while there is still time left for others to respond, and then refreshes the page, the option to answer is displayed again. This is misleading, as the player has already submitted an answer. Ideally, when the player refreshes the page, their previous answer should be shown, and the option to select a new answer should not be displayed.
**Solution:**
1. Implemented a function `get_latest_submitted_answer` to …
=> Prevent re-submission of answers after page refresh by showing previously submitted answer

classquiz/socket_server/__init__.py, frontend/src/routes/play/+page.svelte
Issue:
When a participant joins the activity late, the final result at the end of the activity is different from the admin screen for the late participant.
In this case, when the participant is joining the activity, the scores are considered only after they joined (it's only for the individual) and previous scores of other participants are not added. Therefore, it led to inconsistent scores.
Solution:
Returned all scores of other users when a participant joins late, and assigned populated the scores from storeState to the fetched scores.
=> Fix inconsistent ranking for late joined participant

classquiz/socket_server/__init__.py
During local development for some reason the Socket Server is generating the below error:
```
/home/oscar/.local/share/virtualenvs/games-vv6Brqdh/lib/python3.11/site-packages/socketio/async_server.py:605> exception=KeyError('ping')>
Traceback (most recent call last):
File "/home/oscar/.local/share/virtualenvs/games-vv6Brqdh/lib/python3.11/site-packages/socketio/async_server.py", line 607, in _handle_event_internal
r = await server._trigger_event(data[0], namespace, sid, *data[1:])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/oscar/.local/share/virtualenvs/games-vv6Brqdh/lib/python3.11/site-packages/socketio/async_server.py", line 634, in _trigger_event
ret = await handler(*args)
^^^^^^^^^^^^^^^^^^^^
File …
```
=> Add failback when KeyError: 'ping' is not defined to calculate latency

frontend/src/lib/practice/question.svelte, frontend/src/lib/practice/title_screen.svelte, frontend/src/routes/view/[quiz_id]/+page.svelte
This PR introduces the ability to display images as answer options on both the quiz view and practice routes. The main updates include:
- Image answer options added to quiz and practice routes
- Adjusted styling for the title and description on the practice route
- Introduced logic to handle both text and image answer types
- Minor style adjustments for better UI consistency
=> Add Image-Based Answer Options to Activity View and Practice Routes

frontend/src/lib/play/question.svelte, frontend/src/lib/play/questions/check.svelte
- Added support for displaying images in check choice questions.
- Updated the UI to show image answers using `MediaComponent` on both check choice questions and result displays.
- Enhanced conditional rendering logic for answers with image types, ensuring images are correctly displayed or default icons are shown when appropriate.
- Cleaned up duplicate code for displaying text or images in response areas.
=> Display Images on Check Choice Questions and Results

frontend/src/lib/play/question.svelte
**Problem:**
Users on mobile devices, especially iPhones, are experiencing difficulty scrolling down to the submit button in order-type questions (`QuizQuestionType.ORDER`). When they attempt to scroll by touching over the answer elements (divs, buttons, or SVGs), the page doesn't scroll. This is because touch events on these interactive elements prevent the default scrolling behavior, making it challenging or impossible for users to access the submit button and submit their answers.
**Cause:**
On iOS devices, interactive elements like buttons with touch event listeners can interfere with the default scrolling mechanism. When a user touches these elements, the touch events are captured, and if not properly configured, they can block the scrolling action. Additionally, using …
=> Fix scrolling issue on mobile devices for order-type questions

frontend/src/lib/editor/OrderEditorPart.svelte
This PR introduces a drag-and-drop editor that allows content creators to:
- Add, edit, reorder, and delete answers dynamically in the editor like before.
- Drag and drop answers for easy reordering, with smooth transitions and visual feedback for drag actions.
- Set a default color scheme for answers, with options to customize colors using a color picker like before.
- Improved visual cues for empty answer fields and reactivity enhancements.
- Integrated `svelte-dnd-action` to handle drag-and-drop functionality.
- Added color customization with a set of default colors for answers (`#FFA800`, `#00A3FF`, `#FF1D38`, `#00D749`).
- Implemented visual feedback for drag operations and answer modifications (e.g., scaling and placeholder styles for empty inputs).
- Handled character limits in …
=> Drag and Drop Editor for Order Question Answers

frontend/src/lib/play/join.svelte, frontend/src/routes/+layout.svelte, frontend/src/routes/play/+page.svelte
There was a problem getting from the client side the current game state using a fetch request. This was generating that the participant didn't get the latest game state from the server after reconnection and we were only relying on the local storage. After this fix reconnecting and getting the game state should be more smooth.
- **Fixed fetchGameState bug**: Adjusted fetch calls to execute only on the client side, preventing SSR issues with relative URLs.
- **Removed unused CSS**: Cleaned up unused CSS selectors to improve readability and performance.
- Moved `set_game_pin` function inside `onMount` lifecycle hook to ensure fetch is called only in the browser, fixing an error where fetch was being called during server-side rendering (SSR).
- Refined logic for fetching game state and …
=> Client-Side Fetch Handling and CSS Cleanup

frontend/src/lib/editor/OrderEditorPart.svelte
This PR addresses the issue where different `OrderEditorPart` component instances were incorrectly interacting with each other on multiple cards. Previously, editing the answers in one card would inadvertently affect the answers in other cards. 
- Updated the reactive logic in `OrderEditorPart.svelte` to ensure `items` are recalculated only when `selected_question` changes.
- Introduced a `prevSelectedQuestion` tracker to isolate updates to the correct component instance, ensuring that answers on separate cards remain independent.
- Fixed a bug that was preventing users from editing answer text properly by eliminating unnecessary reactivity on typing.
These changes ensure that each card with an `OrderEditorPart` behaves as expected, without cross-instance interference, and users can now …
=> Fix OrderEditorPart component to handle multiple card instances independently

classquiz/socket_server/__init__.py, frontend/src/lib/admin.svelte, frontend/src/lib/i18n/locales/de.json, frontend/src/lib/i18n/locales/en.json, frontend/src/lib/i18n/locales/es.json, frontend/src/lib/i18n/locales/fr.json, frontend/src/lib/i18n/locales/hu.json, frontend/src/lib/i18n/locales/it.json, frontend/src/lib/i18n/locales/ja.json, frontend/src/lib/i18n/locales/nb_NO.json, frontend/src/lib/i18n/locales/nl.json, frontend/src/lib/i18n/locales/pl.json, frontend/src/lib/i18n/locales/pt.json, frontend/src/lib/i18n/locales/tr.json, frontend/src/lib/i18n/locales/vi.json, frontend/src/lib/play/admin/controls.svelte, frontend/src/lib/play/admin/game_not_started.svelte, frontend/src/routes/admin/+page.svelte
This PR addresses the issue where the player count could be incorrectly inflated due to players rejoining the game with a new session ID (sid). Previously, the player count was calculated using the Redis `scard` function, which counts all player entries, including those from reconnections.
- Introduced a helper function `get_unique_player_count` to calculate the number of unique players based on their usernames, ensuring that reconnections do not affect the player count.
- Updated the `submit_answer` function to use this helper function when calculating the `player_count`, ensuring accurate answer tracking based on unique participants.
- **Backend**: `classquiz/socket_server/__init__.py`
- Added `get_unique_player_count` to count unique players.
- Updated `submit_answer` to utilize this …
=> Improve Player Count Calculation to Avoid Duplicate Entries

classquiz/routers/game_state.py, frontend/src/lib/socket.ts, frontend/src/routes/play/+page.svelte
This PR addresses the issue of Socket.IO disconnection on iPhone devices when the screen locks and resumes. It ensures that the socket connection is properly re-established when the participant unlocks the phone and returns to the activity.
**Key Changes:**
1. **Socket Reconnection for iPhone Hibernate:**
- Implemented socket reconnection logic in `socket.ts` using `Socket.IO` options, including infinite reconnection attempts and delays.
- Added `visibilitychange` event listener in the Svelte page to trigger a reconnection attempt when the user unlocks the device or returns to the page after it was hidden.
- Rejoin the activity session upon successful reconnection to ensure continuity for the participant.
2. **Game State Endpoint Update:**
- Added missing parameters to the `/game_state` …
=> Ensure Socket Reconnection After iPhone Lock/Unlock & Add Missing Game Parameters to Game State

frontend/src/lib/play/question.svelte, frontend/src/lib/play/title.svelte
1. Disable Fullscreen mode for image options on participant's screen.
2. Fix image class not working when on title screen. changed "css_classes" to "class".
=> Disable fullscreen mode for image options

classquiz/routers/game_state.py, frontend/src/routes/play/+page.svelte
- Fixes local storage conflicts generated by #135
- **Fixes:** Avoid resetting `selected_answer` when the game is rejoined, ensuring a smoother user experience during game reconnection.
- **State Handling:** Prevent infinite loops caused by continuous restore state calls by removing unnecessary storage saves that were generating multiple rejoin game events.
- **Backend Sync:** Ensure game status is validated through the backend instead of relying on local storage for end-of-game checks, improving reliability.
- **Code Clean-Up:** Removed commented-out code and unnecessary fields from the `game_state` endpoint.
- **Reconnection Logic:** Added logic to avoid multiple rejoin events and ensured a single reconnection process.
- **Debugging:** Added console logs for better traceability during …
=> Prevent Restore State Infinite Loop and Improve Game State Handling

classquiz/routers/game_state.py, classquiz/socket_server/__init__.py, frontend/src/routes/play/+page.svelte
There was a problem when the participant was disconnected and rejoined the game at the end and the scores were not updated.
This PR ensures the scores are sent from the server when presenting the final results.
=> Send scores form the server when showing final results
